/**
 * Database alimenti locale — valori per 100 g (fonte: tabelle CREA/USDA, arrotondati).
 * kcal, p = proteine g, c = carboidrati g, f = grassi g
 * portion = porzione tipica in grammi
 * unit    = peso di un pezzo in grammi (per "2 uova", "una mela"…), se contabile
 * alias   = nomi alternativi per ricerca e dettatura vocale
 * meals   = pasti per cui l'alimento è un suggerimento sensato
 * cat     = categoria (per emoji e filtri)
 */
const FOOD_DB = [
  // ---- Fonti proteiche magre ----
  { name: "Petto di pollo",            kcal: 100, p: 23.0, c: 0.0,  f: 1.0,  portion: 150, alias: ["pollo"], cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Coscia di pollo (senza pelle)", kcal: 120, p: 18.0, c: 0.0, f: 5.5, portion: 150, cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Fesa di tacchino",          kcal: 107, p: 24.0, c: 0.0,  f: 1.2,  portion: 150, alias: ["tacchino"], cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Manzo magro",               kcal: 129, p: 21.0, c: 0.0,  f: 5.0,  portion: 150, alias: ["manzo"], cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Hamburger di manzo",        kcal: 250, p: 17.0, c: 0.0,  f: 20.0, portion: 100, unit: 100, cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Lonza di maiale",           kcal: 157, p: 21.0, c: 0.0,  f: 8.0,  portion: 150, alias: ["maiale"], cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Vitello",                   kcal: 107, p: 20.7, c: 0.0,  f: 2.7,  portion: 150, cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Salsiccia",                 kcal: 304, p: 15.0, c: 1.0,  f: 27.0, portion: 100, unit: 80, cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Tofu",                      kcal: 76,  p: 8.0,  c: 2.0,  f: 4.5,  portion: 120, cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Seitan",                    kcal: 122, p: 21.0, c: 3.0,  f: 2.0,  portion: 120, cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Tempeh",                    kcal: 193, p: 19.0, c: 9.0,  f: 11.0, portion: 100, cat: "proteine", meals: ["pranzo", "cena"] },
  { name: "Proteine in polvere (whey)",kcal: 380, p: 80.0, c: 6.0,  f: 5.0,  portion: 30,  alias: ["whey", "proteine"], cat: "integr.", meals: ["colazione", "spuntino"] },

  // ---- Pesce ----
  { name: "Merluzzo",                  kcal: 82,  p: 17.0, c: 0.0,  f: 0.9,  portion: 180, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Salmone",                   kcal: 185, p: 20.0, c: 0.0,  f: 12.0, portion: 125, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Salmone affumicato",        kcal: 147, p: 23.0, c: 0.0,  f: 6.0,  portion: 80,  cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Tonno al naturale",         kcal: 103, p: 24.0, c: 0.0,  f: 0.8,  portion: 80,  alias: ["tonno"], cat: "pesce", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Tonno sott'olio (sgocciolato)", kcal: 192, p: 25.0, c: 0.0, f: 10.0, portion: 80, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Orata",                     kcal: 100, p: 19.7, c: 0.0,  f: 2.5,  portion: 180, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Branzino",                  kcal: 97,  p: 18.0, c: 0.0,  f: 2.5,  portion: 180, alias: ["spigola"], cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Sgombro",                   kcal: 168, p: 17.0, c: 0.0,  f: 11.0, portion: 120, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Pesce spada",               kcal: 120, p: 20.0, c: 0.0,  f: 4.0,  portion: 150, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Sogliola",                  kcal: 86,  p: 17.0, c: 0.0,  f: 1.5,  portion: 180, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Alici",                     kcal: 96,  p: 16.8, c: 0.0,  f: 2.6,  portion: 100, alias: ["acciughe"], cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Polpo",                     kcal: 82,  p: 15.0, c: 2.0,  f: 1.0,  portion: 150, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Calamari",                  kcal: 80,  p: 15.5, c: 1.0,  f: 1.5,  portion: 150, cat: "pesce", meals: ["pranzo", "cena"] },
  { name: "Gamberi",                   kcal: 85,  p: 18.0, c: 0.5,  f: 1.0,  portion: 120, alias: ["gamberetti"], cat: "pesce", meals: ["pranzo", "cena"] },

  // ---- Uova ----
  { name: "Uova",                      kcal: 128, p: 12.5, c: 0.5,  f: 8.7,  portion: 120, unit: 60, alias: ["uovo"], cat: "uova", meals: ["colazione", "pranzo", "cena"] },
  { name: "Albume d'uovo",             kcal: 43,  p: 10.7, c: 0.7,  f: 0.2,  portion: 150, alias: ["albumi"], cat: "uova", meals: ["colazione", "cena"] },
  { name: "Frittata",                  kcal: 190, p: 12.0, c: 1.5,  f: 15.0, portion: 150, cat: "uova", meals: ["pranzo", "cena"] },

  // ---- Salumi ----
  { name: "Bresaola",                  kcal: 151, p: 32.0, c: 0.0,  f: 2.0,  portion: 50,  cat: "salumi", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Prosciutto crudo sgrassato",kcal: 145, p: 27.0, c: 0.0,  f: 4.0,  portion: 50,  alias: ["prosciutto crudo", "crudo"], cat: "salumi", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Prosciutto cotto",          kcal: 215, p: 19.8, c: 0.9,  f: 14.7, portion: 50,  alias: ["cotto"], cat: "salumi", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Speck",                     kcal: 300, p: 30.0, c: 0.5,  f: 19.5, portion: 50,  cat: "salumi", meals: ["pranzo", "cena"] },
  { name: "Salame",                    kcal: 384, p: 26.0, c: 1.0,  f: 31.0, portion: 50,  cat: "salumi", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Mortadella",                kcal: 288, p: 15.0, c: 1.0,  f: 25.0, portion: 50,  cat: "salumi", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Fesa di tacchino affettata",kcal: 104, p: 22.0, c: 1.0,  f: 1.5,  portion: 50,  cat: "salumi", meals: ["pranzo", "cena", "spuntino"] },

  // ---- Latticini ----
  { name: "Yogurt greco 0%",           kcal: 57,  p: 10.0, c: 3.9,  f: 0.2,  portion: 170, alias: ["yogurt greco"], cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Yogurt greco 2%",           kcal: 73,  p: 9.5,  c: 4.0,  f: 2.0,  portion: 170, cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Yogurt greco 5% (intero)",  kcal: 97,  p: 9.0,  c: 3.8,  f: 5.0,  portion: 170, alias: ["yogurt greco intero"], cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Yogurt magro",              kcal: 36,  p: 4.0,  c: 5.0,  f: 0.1,  portion: 125, unit: 125, cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Yogurt bianco intero",      kcal: 66,  p: 3.8,  c: 4.3,  f: 3.9,  portion: 125, unit: 125, alias: ["yogurt"], cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Yogurt alla frutta",        kcal: 88,  p: 3.0,  c: 14.0, f: 2.0,  portion: 125, unit: 125, cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Skyr",                      kcal: 63,  p: 11.0, c: 4.0,  f: 0.2,  portion: 150, cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Kefir",                     kcal: 64,  p: 3.3,  c: 4.7,  f: 3.5,  portion: 200, cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Fiocchi di latte",          kcal: 98,  p: 11.0, c: 3.4,  f: 4.3,  portion: 150, cat: "latticini", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Ricotta vaccina",           kcal: 146, p: 11.0, c: 3.5,  f: 10.0, portion: 100, alias: ["ricotta"], cat: "latticini", meals: ["colazione", "pranzo", "cena"] },
  { name: "Mozzarella",                kcal: 253, p: 18.7, c: 0.7,  f: 19.5, portion: 100, unit: 125, cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Mozzarella light",          kcal: 163, p: 20.0, c: 1.0,  f: 9.0,  portion: 100, unit: 125, cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Mozzarella di bufala",      kcal: 288, p: 16.5, c: 0.8,  f: 24.0, portion: 100, unit: 125, alias: ["bufala"], cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Burrata",                   kcal: 300, p: 13.0, c: 2.0,  f: 27.0, portion: 100, unit: 125, cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Stracchino",                kcal: 300, p: 18.0, c: 1.0,  f: 25.0, portion: 50,  cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Scamorza",                  kcal: 334, p: 25.0, c: 1.0,  f: 25.6, portion: 70,  cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Feta",                      kcal: 264, p: 14.0, c: 4.0,  f: 21.0, portion: 50,  cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Formaggio spalmabile",      kcal: 253, p: 6.0,  c: 4.0,  f: 24.0, portion: 30,  alias: ["philadelphia"], cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Formaggio spalmabile light", kcal: 156, p: 7.5, c: 5.0,  f: 11.5, portion: 30,  alias: ["philadelphia light"], cat: "latticini", meals: ["colazione", "spuntino"] },
  { name: "Ricotta light",             kcal: 110, p: 10.5, c: 3.5,  f: 6.0,  portion: 100, cat: "latticini", meals: ["colazione", "pranzo", "cena"] },
  { name: "Parmigiano Reggiano",       kcal: 392, p: 33.0, c: 0.0,  f: 28.0, portion: 20,  alias: ["parmigiano"], cat: "latticini", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Grana Padano",              kcal: 398, p: 33.0, c: 0.0,  f: 29.0, portion: 20,  alias: ["grana"], cat: "latticini", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Pecorino",                  kcal: 387, p: 28.0, c: 0.0,  f: 30.0, portion: 20,  cat: "latticini", meals: ["pranzo", "cena"] },
  { name: "Burro",                     kcal: 758, p: 0.8,  c: 1.0,  f: 83.0, portion: 10,  cat: "latticini", meals: ["colazione"] },
  { name: "Latte parzialmente scremato", kcal: 46, p: 3.3, c: 5.0,  f: 1.5,  portion: 200, alias: ["latte"], cat: "latticini", meals: ["colazione"] },
  { name: "Latte intero",              kcal: 64,  p: 3.3,  c: 4.9,  f: 3.6,  portion: 200, cat: "latticini", meals: ["colazione"] },
  { name: "Latte scremato",            kcal: 36,  p: 3.6,  c: 5.0,  f: 0.2,  portion: 200, cat: "latticini", meals: ["colazione"] },
  { name: "Latte senza lattosio",      kcal: 46,  p: 3.3,  c: 5.0,  f: 1.5,  portion: 200, cat: "latticini", meals: ["colazione"] },
  { name: "Latte di soia",             kcal: 32,  p: 3.0,  c: 1.5,  f: 1.8,  portion: 200, cat: "latticini", meals: ["colazione"] },
  { name: "Latte di mandorla",         kcal: 24,  p: 0.5,  c: 3.0,  f: 1.1,  portion: 200, cat: "latticini", meals: ["colazione"] },
  { name: "Latte d'avena",             kcal: 47,  p: 0.8,  c: 7.0,  f: 1.5,  portion: 200, alias: ["latte avena"], cat: "latticini", meals: ["colazione"] },

  // ---- Legumi ----
  { name: "Ceci cotti",                kcal: 120, p: 7.0,  c: 18.0, f: 2.4,  portion: 150, alias: ["ceci"], cat: "legumi", meals: ["pranzo", "cena"] },
  { name: "Lenticchie cotte",          kcal: 92,  p: 6.9,  c: 16.0, f: 0.4,  portion: 150, alias: ["lenticchie"], cat: "legumi", meals: ["pranzo", "cena"] },
  { name: "Fagioli cotti",             kcal: 91,  p: 6.5,  c: 16.0, f: 0.5,  portion: 150, alias: ["fagioli"], cat: "legumi", meals: ["pranzo", "cena"] },
  { name: "Piselli",                   kcal: 81,  p: 5.4,  c: 14.0, f: 0.4,  portion: 150, cat: "legumi", meals: ["pranzo", "cena"] },
  { name: "Fave",                      kcal: 71,  p: 5.2,  c: 12.0, f: 0.4,  portion: 150, cat: "legumi", meals: ["pranzo", "cena"] },
  { name: "Edamame",                   kcal: 121, p: 11.0, c: 9.0,  f: 5.0,  portion: 100, cat: "legumi", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Lupini",                    kcal: 114, p: 16.0, c: 7.0,  f: 2.4,  portion: 100, cat: "legumi", meals: ["spuntino"] },
  { name: "Hummus",                    kcal: 166, p: 8.0,  c: 14.0, f: 10.0, portion: 50,  cat: "legumi", meals: ["pranzo", "cena", "spuntino"] },

  // ---- Carboidrati ----
  { name: "Pasta di semola (cruda)",   kcal: 353, p: 11.0, c: 71.0, f: 1.4,  portion: 80,  alias: ["pasta", "spaghetti", "penne", "fusilli", "rigatoni"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Pasta integrale (cruda)",   kcal: 335, p: 13.0, c: 63.0, f: 2.5,  portion: 80,  alias: ["pasta integrale"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Pasta cotta",               kcal: 158, p: 5.5,  c: 31.0, f: 0.9,  portion: 200, cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Riso (crudo)",              kcal: 332, p: 6.7,  c: 78.0, f: 0.4,  portion: 80,  alias: ["riso"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Riso basmati (crudo)",      kcal: 349, p: 7.5,  c: 78.0, f: 0.6,  portion: 80,  alias: ["basmati"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Riso venere (crudo)",       kcal: 356, p: 8.5,  c: 74.0, f: 2.5,  portion: 80,  cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Riso cotto",                kcal: 130, p: 2.7,  c: 28.0, f: 0.3,  portion: 150, cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Farro (crudo)",             kcal: 335, p: 15.0, c: 67.0, f: 2.5,  portion: 80,  alias: ["farro"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Orzo (crudo)",              kcal: 319, p: 10.0, c: 70.0, f: 1.4,  portion: 80,  alias: ["orzo"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Quinoa (cruda)",            kcal: 368, p: 14.0, c: 64.0, f: 6.0,  portion: 70,  alias: ["quinoa"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Couscous (crudo)",          kcal: 376, p: 13.0, c: 72.0, f: 1.0,  portion: 80,  alias: ["couscous", "cuscus"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Polenta (cotta)",           kcal: 90,  p: 2.0,  c: 19.0, f: 0.5,  portion: 200, alias: ["polenta"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Gnocchi di patate",         kcal: 149, p: 3.8,  c: 32.0, f: 0.6,  portion: 200, alias: ["gnocchi"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Pane integrale",            kcal: 243, p: 8.5,  c: 44.0, f: 2.0,  portion: 60,  unit: 30, cat: "pane", meals: ["colazione", "pranzo", "cena"] },
  { name: "Pane bianco",               kcal: 275, p: 8.0,  c: 55.0, f: 1.0,  portion: 60,  unit: 30, alias: ["pane", "panino"], cat: "pane", meals: ["colazione", "pranzo", "cena"] },
  { name: "Pane di segale",            kcal: 219, p: 6.0,  c: 45.0, f: 1.7,  portion: 60,  unit: 30, cat: "pane", meals: ["colazione", "pranzo", "cena"] },
  { name: "Piadina",                   kcal: 320, p: 8.0,  c: 54.0, f: 9.0,  portion: 80,  unit: 80, cat: "pane", meals: ["pranzo", "cena"] },
  { name: "Grissini",                  kcal: 431, p: 12.0, c: 69.0, f: 12.0, portion: 25,  unit: 8,  cat: "pane", meals: ["spuntino"] },
  { name: "Taralli",                   kcal: 438, p: 9.0,  c: 60.0, f: 18.0, portion: 40,  unit: 10, cat: "pane", meals: ["spuntino"] },
  { name: "Fiocchi d'avena",           kcal: 389, p: 13.0, c: 66.0, f: 7.0,  portion: 40,  alias: ["avena"], cat: "cereali", meals: ["colazione"] },
  { name: "Cornflakes",                kcal: 378, p: 7.0,  c: 84.0, f: 0.8,  portion: 30,  alias: ["cereali"], cat: "cereali", meals: ["colazione"] },
  { name: "Muesli",                    kcal: 364, p: 10.0, c: 66.0, f: 6.0,  portion: 50,  cat: "cereali", meals: ["colazione"] },
  { name: "Granola",                   kcal: 471, p: 10.0, c: 58.0, f: 20.0, portion: 50,  cat: "cereali", meals: ["colazione"] },
  { name: "Gallette di riso",          kcal: 387, p: 8.0,  c: 82.0, f: 1.0,  portion: 20,  unit: 10, alias: ["gallette"], cat: "cereali", meals: ["colazione", "spuntino"] },
  { name: "Mais dolce",                kcal: 86,  p: 3.2,  c: 19.0, f: 1.2,  portion: 80,  alias: ["mais"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Patate",                    kcal: 85,  p: 2.0,  c: 18.0, f: 0.1,  portion: 250, unit: 200, alias: ["patata"], cat: "cereali", meals: ["pranzo", "cena"] },
  { name: "Patate dolci",              kcal: 86,  p: 1.6,  c: 20.0, f: 0.1,  portion: 250, unit: 200, cat: "cereali", meals: ["pranzo", "cena"] },

  // ---- Frutta ----
  { name: "Banana",                    kcal: 89,  p: 1.1,  c: 23.0, f: 0.3,  portion: 120, unit: 120, alias: ["banane"], cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Mela",                      kcal: 52,  p: 0.3,  c: 14.0, f: 0.2,  portion: 180, unit: 180, alias: ["mele"], cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Arancia",                   kcal: 47,  p: 0.9,  c: 12.0, f: 0.1,  portion: 150, unit: 150, alias: ["arance"], cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Pera",                      kcal: 57,  p: 0.4,  c: 15.0, f: 0.1,  portion: 160, unit: 160, alias: ["pere"], cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Kiwi",                      kcal: 61,  p: 1.1,  c: 15.0, f: 0.5,  portion: 100, unit: 100, cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Pesca",                     kcal: 39,  p: 0.9,  c: 9.5,  f: 0.1,  portion: 150, unit: 150, alias: ["pesche"], cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Albicocca",                 kcal: 48,  p: 1.4,  c: 11.0, f: 0.4,  portion: 80,  unit: 40, alias: ["albicocche"], cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Mandarino",                 kcal: 53,  p: 0.8,  c: 13.0, f: 0.3,  portion: 100, unit: 80, alias: ["mandarini", "clementine"], cat: "frutta", meals: ["spuntino"] },
  { name: "Anguria",                   kcal: 30,  p: 0.6,  c: 7.5,  f: 0.2,  portion: 300, cat: "frutta", meals: ["spuntino"] },
  { name: "Melone",                    kcal: 34,  p: 0.8,  c: 8.0,  f: 0.2,  portion: 200, cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Ananas",                    kcal: 50,  p: 0.5,  c: 13.0, f: 0.1,  portion: 150, cat: "frutta", meals: ["spuntino"] },
  { name: "Mango",                     kcal: 60,  p: 0.8,  c: 15.0, f: 0.4,  portion: 150, cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Ciliegie",                  kcal: 63,  p: 1.1,  c: 16.0, f: 0.2,  portion: 100, cat: "frutta", meals: ["spuntino"] },
  { name: "Prugna",                    kcal: 46,  p: 0.7,  c: 11.0, f: 0.3,  portion: 80,  unit: 60, alias: ["prugne", "susine"], cat: "frutta", meals: ["spuntino"] },
  { name: "Fichi",                     kcal: 74,  p: 0.8,  c: 19.0, f: 0.3,  portion: 100, unit: 50, cat: "frutta", meals: ["spuntino"] },
  { name: "Cachi",                     kcal: 70,  p: 0.6,  c: 18.0, f: 0.3,  portion: 150, unit: 150, alias: ["caco"], cat: "frutta", meals: ["spuntino"] },
  { name: "Melograno",                 kcal: 83,  p: 1.7,  c: 19.0, f: 1.2,  portion: 100, cat: "frutta", meals: ["spuntino"] },
  { name: "Fragole",                   kcal: 32,  p: 0.7,  c: 8.0,  f: 0.3,  portion: 150, cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Mirtilli",                  kcal: 57,  p: 0.7,  c: 14.0, f: 0.3,  portion: 100, cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Frutti di bosco",           kcal: 45,  p: 1.0,  c: 10.0, f: 0.4,  portion: 100, cat: "frutta", meals: ["colazione", "spuntino"] },
  { name: "Uva",                       kcal: 69,  p: 0.7,  c: 18.0, f: 0.2,  portion: 120, cat: "frutta", meals: ["spuntino"] },
  { name: "Datteri",                   kcal: 282, p: 2.5,  c: 75.0, f: 0.4,  portion: 30,  unit: 8, cat: "frutta", meals: ["spuntino"] },
  { name: "Uvetta",                    kcal: 299, p: 3.0,  c: 79.0, f: 0.5,  portion: 30,  cat: "frutta", meals: ["colazione", "spuntino"] },

  // ---- Verdura ----
  { name: "Zucchine",                  kcal: 17,  p: 1.2,  c: 3.1,  f: 0.3,  portion: 200, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Melanzane",                 kcal: 25,  p: 1.0,  c: 6.0,  f: 0.2,  portion: 200, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Insalata mista",            kcal: 15,  p: 1.4,  c: 2.9,  f: 0.2,  portion: 100, alias: ["insalata", "lattuga"], cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Rucola",                    kcal: 25,  p: 2.6,  c: 3.7,  f: 0.7,  portion: 50,  cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Pomodori",                  kcal: 18,  p: 0.9,  c: 3.9,  f: 0.2,  portion: 150, unit: 100, alias: ["pomodoro"], cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Broccoli",                  kcal: 34,  p: 2.8,  c: 7.0,  f: 0.4,  portion: 200, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Cavolfiore",                kcal: 25,  p: 1.9,  c: 5.0,  f: 0.3,  portion: 200, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Spinaci",                   kcal: 23,  p: 2.9,  c: 3.6,  f: 0.4,  portion: 150, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Verza",                     kcal: 27,  p: 2.0,  c: 5.0,  f: 0.1,  portion: 200, alias: ["cavolo"], cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Carote",                    kcal: 41,  p: 0.9,  c: 10.0, f: 0.2,  portion: 150, unit: 80, alias: ["carota"], cat: "verdura", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Peperoni",                  kcal: 26,  p: 1.0,  c: 6.0,  f: 0.3,  portion: 150, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Cetrioli",                  kcal: 15,  p: 0.7,  c: 3.6,  f: 0.1,  portion: 150, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Finocchi",                  kcal: 31,  p: 1.2,  c: 7.0,  f: 0.2,  portion: 200, cat: "verdura", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Funghi champignon",         kcal: 22,  p: 3.1,  c: 3.3,  f: 0.3,  portion: 150, alias: ["funghi"], cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Cipolla",                   kcal: 40,  p: 1.1,  c: 9.0,  f: 0.1,  portion: 50,  cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Asparagi",                  kcal: 20,  p: 2.2,  c: 3.9,  f: 0.1,  portion: 200, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Fagiolini",                 kcal: 31,  p: 1.8,  c: 7.0,  f: 0.2,  portion: 200, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Carciofi",                  kcal: 47,  p: 3.3,  c: 10.5, f: 0.2,  portion: 150, cat: "verdura", meals: ["pranzo", "cena"] },
  { name: "Zucca",                     kcal: 26,  p: 1.0,  c: 6.5,  f: 0.1,  portion: 200, cat: "verdura", meals: ["pranzo", "cena"] },

  // ---- Grassi buoni ----
  { name: "Olio extravergine d'oliva", kcal: 884, p: 0.0,  c: 0.0,  f: 100.0, portion: 10, alias: ["olio", "olio evo", "olio d'oliva"], cat: "grassi", meals: ["pranzo", "cena"] },
  { name: "Maionese",                  kcal: 690, p: 1.0,  c: 2.0,  f: 75.0, portion: 15,  cat: "grassi", meals: ["pranzo", "cena"] },
  { name: "Maionese light",            kcal: 340, p: 1.0,  c: 8.0,  f: 33.0, portion: 15,  cat: "grassi", meals: ["pranzo", "cena"] },
  { name: "Ketchup",                   kcal: 100, p: 1.2,  c: 24.0, f: 0.1,  portion: 15,  cat: "grassi", meals: ["pranzo", "cena"] },
  { name: "Pesto",                     kcal: 450, p: 5.0,  c: 6.0,  f: 45.0, portion: 30,  cat: "grassi", meals: ["pranzo", "cena"] },
  { name: "Avocado",                   kcal: 160, p: 2.0,  c: 8.5,  f: 15.0, portion: 100, unit: 200, cat: "grassi", meals: ["colazione", "pranzo", "cena"] },
  { name: "Olive",                     kcal: 145, p: 1.0,  c: 4.0,  f: 15.0, portion: 25,  unit: 4, cat: "grassi", meals: ["pranzo", "cena", "spuntino"] },
  { name: "Mandorle",                  kcal: 603, p: 22.0, c: 4.6,  f: 55.0, portion: 20,  unit: 1.2, cat: "frutta secca", meals: ["colazione", "spuntino"] },
  { name: "Noci",                      kcal: 654, p: 15.0, c: 7.0,  f: 65.0, portion: 20,  unit: 5, cat: "frutta secca", meals: ["colazione", "spuntino"] },
  { name: "Nocciole",                  kcal: 655, p: 13.8, c: 6.1,  f: 64.0, portion: 20,  unit: 1.3, cat: "frutta secca", meals: ["spuntino"] },
  { name: "Pistacchi",                 kcal: 560, p: 20.0, c: 28.0, f: 45.0, portion: 25,  cat: "frutta secca", meals: ["spuntino"] },
  { name: "Anacardi",                  kcal: 553, p: 18.0, c: 30.0, f: 44.0, portion: 25,  cat: "frutta secca", meals: ["spuntino"] },
  { name: "Arachidi",                  kcal: 567, p: 26.0, c: 16.0, f: 49.0, portion: 25,  cat: "frutta secca", meals: ["spuntino"] },
  { name: "Burro d'arachidi",          kcal: 588, p: 25.0, c: 20.0, f: 50.0, portion: 20,  alias: ["burro di arachidi"], cat: "frutta secca", meals: ["colazione", "spuntino"] },
  { name: "Semi di chia",              kcal: 486, p: 17.0, c: 42.0, f: 31.0, portion: 15,  cat: "frutta secca", meals: ["colazione"] },
  { name: "Semi di zucca",             kcal: 559, p: 30.0, c: 11.0, f: 49.0, portion: 15,  cat: "frutta secca", meals: ["spuntino"] },

  // ---- Piatti comuni ----
  { name: "Pizza margherita",          kcal: 271, p: 11.0, c: 33.0, f: 10.0, portion: 300, unit: 300, alias: ["pizza"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Pasta al pomodoro",         kcal: 110, p: 3.5,  c: 20.0, f: 1.8,  portion: 300, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Pasta al pesto",            kcal: 165, p: 5.0,  c: 22.0, f: 6.5,  portion: 300, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Pasta alla carbonara",      kcal: 195, p: 8.5,  c: 22.0, f: 8.5,  portion: 320, alias: ["carbonara"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Lasagne al forno",          kcal: 165, p: 9.0,  c: 15.0, f: 8.0,  portion: 300, alias: ["lasagne"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Risotto",                   kcal: 130, p: 3.0,  c: 22.0, f: 3.3,  portion: 300, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Minestrone",                kcal: 40,  p: 2.0,  c: 6.5,  f: 0.7,  portion: 300, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Zuppa di legumi",           kcal: 70,  p: 4.5,  c: 11.0, f: 1.0,  portion: 300, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Insalata di riso",          kcal: 145, p: 4.5,  c: 22.0, f: 4.5,  portion: 250, cat: "piatti", meals: ["pranzo"] },
  { name: "Purè di patate",            kcal: 100, p: 2.5,  c: 15.0, f: 3.5,  portion: 200, alias: ["pure"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Parmigiana di melanzane",   kcal: 140, p: 6.0,  c: 8.0,  f: 9.5,  portion: 250, alias: ["parmigiana"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Cotoletta alla milanese",   kcal: 250, p: 18.0, c: 13.0, f: 14.0, portion: 150, alias: ["cotoletta"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Panino con prosciutto",     kcal: 260, p: 13.0, c: 33.0, f: 8.0,  portion: 150, unit: 150, cat: "piatti", meals: ["pranzo"] },
  { name: "Toast prosciutto e formaggio", kcal: 260, p: 12.0, c: 28.0, f: 11.0, portion: 130, unit: 130, alias: ["toast"], cat: "piatti", meals: ["colazione", "pranzo", "spuntino"] },
  { name: "Hamburger completo (panino)", kcal: 250, p: 12.0, c: 25.0, f: 11.0, portion: 250, unit: 250, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Kebab",                     kcal: 215, p: 12.0, c: 18.0, f: 10.0, portion: 300, unit: 300, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Sushi misto",               kcal: 150, p: 7.0,  c: 26.0, f: 2.5,  portion: 200, alias: ["sushi"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Patatine fritte",           kcal: 312, p: 3.9,  c: 37.0, f: 16.7, portion: 150, alias: ["patatine"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Smash burger",              kcal: 270, p: 14.0, c: 19.0, f: 15.0, portion: 250, unit: 250, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Poke bowl",                 kcal: 120, p: 8.0,  c: 14.0, f: 3.5,  portion: 400, alias: ["poke"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Burrito",                   kcal: 180, p: 9.0,  c: 20.0, f: 7.0,  portion: 300, unit: 300, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Tacos",                     kcal: 220, p: 11.0, c: 20.0, f: 11.0, portion: 150, unit: 75, alias: ["taco"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Ramen",                     kcal: 90,  p: 5.0,  c: 11.0, f: 2.5,  portion: 450, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Hot dog",                   kcal: 250, p: 10.0, c: 25.0, f: 12.0, portion: 200, unit: 200, cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Nuggets di pollo",          kcal: 260, p: 14.0, c: 15.0, f: 16.0, portion: 150, unit: 18, alias: ["nuggets"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Tagliata di manzo",         kcal: 170, p: 24.0, c: 0.5,  f: 8.0,  portion: 250, alias: ["tagliata"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Fritto misto di pesce",     kcal: 220, p: 13.0, c: 15.0, f: 12.0, portion: 250, alias: ["fritto misto"], cat: "piatti", meals: ["pranzo", "cena"] },
  { name: "Club sandwich",             kcal: 230, p: 12.0, c: 22.0, f: 10.0, portion: 250, unit: 250, cat: "piatti", meals: ["pranzo", "cena"] },

  // ---- Dolci e colazione ----
  { name: "Marmellata",                kcal: 240, p: 0.5,  c: 59.0, f: 0.1,  portion: 25,  cat: "dolci", meals: ["colazione"] },
  { name: "Marmellata senza zuccheri", kcal: 120, p: 0.5,  c: 28.0, f: 0.1,  portion: 25,  cat: "dolci", meals: ["colazione"] },
  { name: "Miele",                     kcal: 304, p: 0.6,  c: 80.0, f: 0.0,  portion: 15,  cat: "dolci", meals: ["colazione"] },
  { name: "Zucchero",                  kcal: 392, p: 0.0,  c: 100.0, f: 0.0, portion: 5,   unit: 5, cat: "dolci", meals: ["colazione"] },
  { name: "Biscotti secchi",           kcal: 416, p: 7.0,  c: 80.0, f: 8.0,  portion: 30,  unit: 8, alias: ["biscotti"], cat: "dolci", meals: ["colazione", "spuntino"] },
  { name: "Fette biscottate integrali",kcal: 380, p: 12.0, c: 70.0, f: 6.0,  portion: 30,  unit: 10, alias: ["fette biscottate"], cat: "pane", meals: ["colazione"] },
  { name: "Crackers",                  kcal: 428, p: 9.5,  c: 68.0, f: 13.0, portion: 25,  unit: 8, alias: ["cracker"], cat: "pane", meals: ["spuntino"] },
  { name: "Cornetto",                  kcal: 410, p: 7.5,  c: 47.0, f: 21.0, portion: 60,  unit: 60, alias: ["brioche", "croissant", "fagottino al cioccolato", "saccottino"], cat: "dolci", meals: ["colazione"] },
  { name: "Crema alle nocciole",       kcal: 539, p: 6.0,  c: 57.0, f: 31.0, portion: 15,  alias: ["nutella"], cat: "dolci", meals: ["colazione"] },
  { name: "Cioccolato fondente 85%",   kcal: 584, p: 9.0,  c: 24.0, f: 46.0, portion: 20,  alias: ["cioccolato fondente"], cat: "dolci", meals: ["spuntino"] },
  { name: "Cioccolato al latte",       kcal: 545, p: 7.0,  c: 57.0, f: 32.0, portion: 20,  alias: ["cioccolato"], cat: "dolci", meals: ["spuntino"] },
  { name: "Torta margherita",          kcal: 367, p: 7.0,  c: 58.0, f: 12.0, portion: 80,  alias: ["torta"], cat: "dolci", meals: ["colazione", "spuntino"] },
  { name: "Crostata",                  kcal: 380, p: 5.5,  c: 60.0, f: 13.0, portion: 80,  cat: "dolci", meals: ["colazione", "spuntino"] },
  { name: "Merendina",                 kcal: 400, p: 5.0,  c: 55.0, f: 18.0, portion: 35,  unit: 35, cat: "dolci", meals: ["colazione", "spuntino"] },
  { name: "Tiramisù",                  kcal: 290, p: 5.5,  c: 33.0, f: 15.0, portion: 120, cat: "dolci", meals: ["spuntino"] },
  { name: "Gelato alla crema",         kcal: 200, p: 3.8,  c: 24.0, f: 10.0, portion: 100, unit: 60, alias: ["gelato", "gelato artigianale", "pallina"], cat: "dolci", meals: ["spuntino"] },
  { name: "Gelato alla frutta",        kcal: 140, p: 2.0,  c: 28.0, f: 2.5,  portion: 100, unit: 60, alias: ["sorbetto"], cat: "dolci", meals: ["spuntino"] },
  { name: "Gelato al pistacchio",      kcal: 240, p: 6.0,  c: 22.0, f: 15.0, portion: 100, unit: 60, cat: "dolci", meals: ["spuntino"] },
  { name: "Gelato al cioccolato",      kcal: 220, p: 4.5,  c: 26.0, f: 11.0, portion: 100, unit: 60, cat: "dolci", meals: ["spuntino"] },
  { name: "Gelato alla nocciola",      kcal: 230, p: 5.0,  c: 24.0, f: 14.0, portion: 100, unit: 60, cat: "dolci", meals: ["spuntino"] },
  { name: "Cono gelato confezionato",  kcal: 330, p: 4.5,  c: 40.0, f: 17.0, portion: 75,  unit: 75, alias: ["cornetto algida", "cono"], cat: "dolci", meals: ["spuntino"] },
  { name: "Ghiacciolo",                kcal: 80,  p: 0.0,  c: 20.0, f: 0.0,  portion: 70,  unit: 70, cat: "dolci", meals: ["spuntino"] },

  // ---- Bevande ----
  { name: "Caffè espresso",            kcal: 2,   p: 0.1,  c: 0.3,  f: 0.0,  portion: 30,  unit: 30, alias: ["caffe", "espresso"], cat: "bevande", meals: ["colazione", "spuntino"] },
  { name: "Cappuccino",                kcal: 45,  p: 2.5,  c: 4.5,  f: 1.7,  portion: 150, unit: 150, cat: "bevande", meals: ["colazione"] },
  { name: "Succo d'arancia",           kcal: 45,  p: 0.7,  c: 10.0, f: 0.2,  portion: 200, alias: ["succo di frutta", "spremuta"], cat: "bevande", meals: ["colazione", "spuntino"] },
  { name: "Coca cola",                 kcal: 42,  p: 0.0,  c: 10.6, f: 0.0,  portion: 330, unit: 330, alias: ["cola"], cat: "bevande", meals: ["pranzo", "cena"] },
  { name: "Bibita zero",               kcal: 0,   p: 0.0,  c: 0.0,  f: 0.0,  portion: 330, unit: 330, alias: ["coca zero", "cola zero", "coca light"], cat: "bevande", meals: ["pranzo", "cena"] },
  { name: "Tè freddo",                 kcal: 28,  p: 0.0,  c: 7.0,  f: 0.0,  portion: 330, unit: 330, alias: ["the freddo", "estathe"], cat: "bevande", meals: ["pranzo", "spuntino"] },
  { name: "Birra",                     kcal: 43,  p: 0.5,  c: 3.5,  f: 0.0,  portion: 330, unit: 330, cat: "bevande", meals: ["pranzo", "cena"] },
  { name: "Vino rosso",                kcal: 85,  p: 0.1,  c: 2.5,  f: 0.0,  portion: 125, unit: 125, alias: ["vino"], cat: "bevande", meals: ["pranzo", "cena"] },
  { name: "Spritz",                    kcal: 90,  p: 0.0,  c: 8.0,  f: 0.0,  portion: 200, unit: 200, alias: ["aperol"], cat: "bevande", meals: ["cena"] },
];

const CAT_EMOJI = {
  proteine: "🍗", pesce: "🐟", uova: "🥚", salumi: "🥩", latticini: "🥛",
  legumi: "🫘", cereali: "🌾", pane: "🍞", frutta: "🍎", verdura: "🥦",
  grassi: "🫒", "frutta secca": "🥜", dolci: "🍯", piatti: "🍕", "integr.": "🥤",
  bevande: "☕",
};

function foodEmoji(food) {
  return CAT_EMOJI[food.cat] || "🍽️";
}
